# Generated by Django 3.0.8 on 2020-07-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='profile_pic',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
    ]
