# Generated by Django 3.0.8 on 2020-07-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
