# Generated by Django 3.0.8 on 2020-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
    ]
